language: node_js
node_js:
  - '12.13'
cache:
  directories:
    - node_modules
    - '$HOME/.cache'
install:
  - yarn

script:
  - yarn run test

deploy:
  provider: npm
  email: '$NPM_EMIAL'
  api_key: '$NPM_TOKEN'
  cleanup: false
  skip_cleanup: true
  on:
    tags: on
